name: Deploy to Ubuntu PC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        env:
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_SECRET }}
        run: |
          curl -X POST https://mj-dev.site/webhook/pull --connect-timeout 30 --max-time 300 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${WEBHOOK_TOKEN}" \
            -d '{"event": "push"}'
